name: Weekly Build

on:
  schedule:
    # weekly at 0700 PST/1400 UTC on Sunday
    - cron: '0 14 * * 0'


# in the future make this just call the commit workflow, but right now looks a little hacky to do in actions
jobs:
  darglint:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: set up python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: setup test env
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          python -m pip install nox
      - name: run nox darglint
        run: python -m nox -s darglint

        os: [ubuntu-latest, macos-latest]

